### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by Pewa0001** [xHyroM/Uptimo#10]
I decided to test this out and I registered an account. This was my first time but it showed an error saying "Too many accounts added from this IP". Is there a fix because I have never been on this site

**Comment by chobotnice007** [comment]
Try to connect from another IP. Or run your own Uptimo instance. This cannot be fixed. @Pewa001

**Comment by xhyrom** [comment]
This is protection against registering many accounts from the same ip address. So if you have a VPN, use it or wait 1 hour and you will do it again.

**Comment by chobotnice007** [comment]
> This is protection against registering many accounts from the same ip address. So if you have a VPN, use it or wait 1 hour and you will do it again.

Or maces to internet via another IP address.
