### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by ZonaBRDev** [xHyroM/Uptimo#14]
ERR_TOO_MANY_REDIRECTS - i clear all cookies, no solved. 

https://whiteuptime.tk/

**Comment by nxvvvv** [comment]
Hey, do you face this when you go to the repl site? Or is it just the problem faced when using new domain?

**Comment by nxvvvv** [comment]
Hmm i checked and I'm getting good results while using your repl site

**Comment by nxvvvv** [comment]
Also which dns are you using?

**Comment by ZonaBRDev** [comment]
I use Freenom Domains, Dns correct and recommended

**Comment by ZonaBRDev** [comment]
the error performs with the following steps: Enter the site> The Error Happens 

Expectation (Which obviously should happen): Enter the site> Get Login> Place bots

 I use Repl.it 
My domain is registered by freenom, my dns is what repl.it provides the steps

**Comment by ZonaBRDev** [comment]
I've been using repl.it for a long time. Never occurred

**Comment by nxvvvv** [comment]
Yea it's happening to my website too. https://pingus.tk

**Comment by nxvvvv** [comment]
### I found the solution.
1. First go to your website's CloudFlare dashboard.<br>![image (7)](https://user-images.githubusercontent.com/34748927/108349676-4b634080-7209-11eb-85b0-daa2b5892474.png)<br>
2. Then go to SSL/TLS setting.<br>![image](https://user-images.githubusercontent.com/34748927/108350013-af860480-7209-11eb-8de8-f4efcd0313d1.png)<br>
3. Currently the setting is **Flexible**.<br>![image](https://user-images.githubusercontent.com/34748927/108350184-ee1bbf00-7209-11eb-901c-38f7efcbcf93.png)<br>
4. Change it to **Full(strict)**.<br>![image](https://user-images.githubusercontent.com/34748927/108350316-173c4f80-720a-11eb-9d00-bc96caaa3eb0.png)<br>
5. Done. Now your website will be OK!!

@ZonaBRDev

**Comment by nxvvvv** [comment]
@xHyroM you can close the issue.

**Comment by xhyrom** [comment]
Okay

**Comment by xhyrom** [comment]
repl.it received an update and automatically offers an ssl certificate so you have to turn off proxied status on cloudflare.
