### ISSUE TITLE
Nápady na zlepsenie

### ISSUE THREAD

**Issue by ANONYM-ANONYM** [xHyroM/Uptimo#2]
Cc mam par napadov ma zlepšenie:
- [x]  Pridat aktualny stav ze ci je projekt up alebo down
- [ ]  Spravit uptime v % a spravit badges ze kolko % uptime je projekt
- [x]  Pridat notifikacie cez discord, slack webhooky ked projekt bude up/down  [_Aspon spravit example kod vo Wiki ako si spravit vlastne notifikacie cez `/api/check?url=`_  ]
- [x] spravit status badge na aktualny status text a status kod
- [ ]  spravit moznost zmenit text Status v tom badge cez req.query
- [ ] **pridat nastavenie na vlastny ping interval**
Podla mna netreba vzdy pingovat vsetko kazdu 1 min. Hodilo by sa spravit ping interval na vyber napr. 30s, 1 min, 1,5 min, 2 min, 3 min, 5 min, 10 min, 30 min, ...
- [ ] Pridat api kluce pre pridavanie url cez api. (Ze ked chces pridat projekt cez api - musis mat ucet s vygenerovanym api klucom)

**Comment by xhyrom** [comment]
Na všetkom budem pracovať ako prvé budem robiť notiikacie či je Up/Down.
Potom budem pracovať na badge a potom sa uvidí.

**Comment by ANONYM-ANONYM** [comment]
ok

**Comment by iZboxo** [comment]
Přidat na hlavní stránku i **Reset Password** když to je jenom v tom když seš přihlášenej tak je to celkem k ničemu :/

**Comment by Gabe616** [comment]
Ahoj <#765925456263643166> <:BlurpleKek:95048554526> xd

**Comment by Gabe616** [comment]
<a:animateboost:737661539862970410><a:AgrDance:752601469550723103>

**Comment by Gabe616** [comment]
[to je hustý](https://google.com/%00 "lol")

**Comment by iZboxo** [comment]
<:party_blob:708749768226111488>

**Comment by Gabe616** [comment]
[hmmm](https://www.youtube.com/watch?v=dQw4w9WgXcQ) <a:708749795048554526:BlurpleKek:>

**Comment by ANONYM-ANONYM** [comment]
@iZboxo Dobry napad, mozno pridat aj email do register formu a ze ked zabudnes heslo napises email a link na resetnutie hesla ti pride na email napr cez https://nodemailer.com .

**Comment by rejsik99** [comment]
Přidat notifikce přes discord webhooky nebo bota když bude třeba online/offline

**Comment by xhyrom** [comment]
@Rejsik99 toto si už môžeš spraviť sám lebo už existuje https://uptime.hyrousek.tk/api/check?url=tvoja url

**Comment by ANONYM-ANONYM** [comment]
Sprav aj celkovu uptime v % a uptime logy

**Comment by xhyrom** [comment]
Ano všetko bude práve pracujem na obnovenie hesla emailom

**Comment by ANONYM-ANONYM** [comment]
Pridaj aj status kod na ten check

```js
setInterval(() => {
  d.forEach(url => {
    var r = url.split("<")[0]
    fetch(r).then((res) => {
      console.log(`✅ - Succesfully pinged (${r}) | Status:  ${res.status} (${res.statusText}) `)
 }).catch((e) => {
      console.log(`📛 Failed ping (${r}) | Status:  ${res.status} (${res.statusText}) `)
    })
  })
}, 60 * 1000)
```

**Comment by ANONYM-ANONYM** [comment]
Este ze ked zmazes ucet tak sa vsetky linky od toho kto mal ten ucet zmazu automaticky

**Comment by xhyrom** [comment]
Ano to bude

**Comment by xhyrom** [comment]
Iba pri delete alebo aj pri bane?

**Comment by ANONYM-ANONYM** [comment]
len delete a este pridat unban

**Comment by ANONYM-ANONYM** [comment]
a nieco ako warn ze sa tomu userovi zobrazi popup ked sa prihlasi a ma nejaky warning

**Comment by xhyrom** [comment]
Tu je ping.js so statusom:
```js
const db = require("quick.db")
const fetch = require("node-fetch")
const d = db.get("urls")

var check = {
  true: "online",
  false: "offline"
}

setInterval(() => {
  d.forEach(url => {
    var r = url.split("<")[0]
    fetch(r).then(() => {
      var status = db.get(`status_${r}`)
      db.set(`status_${r}`, true)

      console.log(`✅ Succesfully pinged (${r}) | Status: ${check[status]}`)
    }).catch((e) => {
      var status = db.get(`status_${r}`)
      db.set(`status_${r}`, false)
      console.log(`📛 Failed ping (${r}) | Status: ${check[status]}`)
    })
  })
}, 60 * 1000)

d.forEach(url => {
  var r = url.split("<")[0]
  fetch(r).then(() => {
    var status = db.get(`status_${r}`)
    db.set(`status_${r}`, true)
    console.log(`✅ Succesfully pinged (${r}) | Status: ${check[status]}`)
  }).catch((e) => {
    var status = db.get(`status_${r}`)
    db.set(`status_${r}`, false)
    console.log(`📛 Failed ping (${r}) | Status: ${check[status]}`)
  })
})
```

**Comment by ANONYM-ANONYM** [comment]
ok, ale mozes dat ze zapise aj status kod do databazy

**Comment by xhyrom** [comment]
Status či je true/false sa už do databázy zapisuje
```js
db.set(`status_${r}`, true)
```

**Comment by ANONYM-ANONYM** [comment]
ano ale aj presny status kod pri false napr ze ci je 403, 502, ...

**Comment by xhyrom** [comment]
To je blbosť lebo neviem detekovať či je 404 page napríklad alebo či proste nejde

**Comment by xhyrom** [comment]
Práve som spravil že keď deletnete usera tak sa zmažú všetky jeho url - https://github.com/xHyroM/Uptimo/commit/3228c39a7efe4cc56c26f80bf60d773dcd9a0a6c
```js

  if(req.query.type === "delete") {
    const u = db.get("urls")
    var yurl = []

    u.forEach(function(url) {
      var n = url.split("<")[1]
      if(n === req.query.user) {
        yurl.push(url)
      }
    })

    yurl.forEach(function(url) {
      var array = db.get("urls");
      array = array.filter(v => v !== url);
      db.set("urls", array)
      db.delete(`status_${url.split("<")[0]}`)
    })

    console.log(u)
    db.delete(`account_${req.query.user}`)

    return res.render("error", {
        error: false,
        status: 200,
        error: "User succesfully deleted!"
    })
  }
```

**Comment by ANONYM-ANONYM** [comment]
ok

**Comment by ANONYM-ANONYM** [comment]
Mozes pridat aj nieco taketo:
![image](https://user-images.githubusercontent.com/70404616/96335243-a0365500-1077-11eb-9a1b-b45317bc1851.png)

![image](https://user-images.githubusercontent.com/70404616/96335251-b17f6180-1077-11eb-9ca8-0becfedd538b.png)

**Comment by xHyroM** [comment]
pozri status code je aj tak k ničomu ja nedokážem detekovať či je web service unavaible že prebieha maintenance alebo vôbec nejde

**Comment by ANONYM-ANONYM** [comment]
ok

**Comment by xHyroM** [comment]
Dobre spravím to ale nebudem upravovať ping.js iba to spravím ako get pri check

**Comment by ANONYM-ANONYM** [comment]
ok

**Comment by xHyroM** [comment]
Keď je status code 400 status text mám dať aký?

**Comment by ANONYM-ANONYM** [comment]
ja to mam ze ten kod a text zisti z toho node-fetch 
```js
db.set(`status_${r}.s`, true)
      db.set(`status_${r}.code`, res.status)
      db.set(`status_${r}.text`, res.statusText)
```

**Comment by xhyrom** [comment]
Dobre to tam pridám

**Comment by xhyrom** [comment]
@ANONYM-ANONYM

https://github.com/xHyroM/Uptimo/commit/3add38d89fcf6d957f815ef53a4355602b4efb4b - api/check.js
https://github.com/xHyroM/Uptimo/commit/a47cd35e5b622626dc20ed081ee9159d7867691d - ping.js

**Comment by ANONYM-ANONYM** [comment]
Este mozno pridat discord webhook notifikácie
Ze kazdy user si moze nastavit webhook, kde budu chodit motifikacie na vsetky jeho linky ak su online alebo offline

**Comment by xhyrom** [comment]
Už som práve pridal https://github.com/xHyroM/Uptimo/commit/225b4dff51331e5660775ec77fb38bc14e49d458 (badge)
https://github.com/xHyroM/Uptimo/tree/main/badge

**Comment by ANONYM-ANONYM** [comment]
Cc mam dalsie navrhy:
- spravit status badge na aktualny status text a kod
- spravit mozno zmenit text Status v tom badgr cez req.query
- pridat nastavenie na vlastneho ping intervalu

**Comment by xhyrom** [comment]
Pre nové návrhy vytváraj nové issue. Takto je to neprehladné

**Comment by ANONYM-ANONYM** [comment]
@xHyroM Pridal som ich sem: https://github.com/xHyroM/Uptimo/issues/2#issue-723500996

**Comment by chobotnice007** [comment]
> @iZboxo Dobry napad, mozno pridat aj email do register formu a ze ked zabudnes heslo napises email a link na resetnutie hesla ti pride na email napr cez https://nodemailer.com .

Stačí  odeslání přes SMTP.
