### ISSUE TITLE
Suggestion: Use mongodb

### ISSUE THREAD

**Issue by ANONYM-ANONYM** [xHyroM/Uptimo#7]
Navrh: Zmenit quick.db na mongodb
Niekedy sa mi pri hostingu na repl.it stane ze niektore linky sa same zmazu. Napr. pridam link a na druhy den sa prihlasim a zistim ze ten, co som pridal tam uz neni.

**Comment by xhyrom** [comment]
Ok, do večera to bude.

**Comment by xhyrom** [comment]
Ešte keď chcete môžete používať repl.it DB ale toto robiť nebudem príde mi to zbytočné.

**Comment by ANONYM-ANONYM** [comment]
Jj, spravis to cez mongose? Alebo to quickmongo

**Comment by xhyrom** [comment]
Hotovo https://github.com/xHyroM/Uptimo/releases/tag/v3.5 keby niečo vytvor si issue

**Comment by ANONYM-ANONYM** [comment]
@xHyroM Nejako nefunguje /api/check
```{"url":"moja url","status":"online","status_code":503,"status_text":"OFF"}```
vzdy tam je 503 a OFF
 a ani badge nejde

**Comment by xhyrom** [comment]
Vytvor si nové issue dakujem
